import { topoSort, type Graph, type NodeId, type ParamValue, type SlotRef } from "../ir/index.js";
import { AssetRef, isParamRef } from "../ir/types.js";
import { sanitizeIdentifier } from "../builder/builder.js";
import type { NodeDefs } from "../defs/index.js";
import bundledDefsJson from "../nodes/gen/defs.json" with { type: "json" };

/**
 * Emit a readable TypeScript workflow file from Graph IR.
 *
 * `cwf import x.json --ts workflows/foo/workflow.ts` turns an imported
 * workflow into authored source: the TS file becomes the canonical authoring
 * representation, the IR file remains the semantic record (including any
 * preserved `source.raw` metadata that has no TS representation).
 *
 * All connections emit as `unsafeRef(...)` — untyped but correct for typed
 * and raw sources alike (NodeOutput<never> assigns to any input). Agents can
 * rewire with named typed handles when editing the emitted file by hand.
 */
export interface EmitterRegistry {
  /** Module specifier to import these specs from (e.g. "./comfy-nodes/registry.js"). */
  specifier: string;
  /** Node classes this registry provides typed specs for. */
  classes: ReadonlySet<string>;
  /** Identifier the registry exports for each class (defaults to classType). */
  identifiers?: ReadonlyMap<string, string>;
}

export function emitTs(
  g: Graph,
  opts: {
    defs?: NodeDefs;
    moduleName?: string;
    /**
     * Typed-spec registries to import from, in priority order. Nodes whose
     * class appears in none of them (and not in the default
     * "@stepupgaming/comfy-workflows/nodes" registry) are emitted as rawNode()
     * — the emitted file always loads. `cwf import --registry <codegenDir>`
     * wires generated custom-node specs in here automatically.
     */
    registries?: EmitterRegistry[];
  } = {},
): string {
  const defs = opts.defs;
  const registries: EmitterRegistry[] = [
    // Default: the package's built-in registry.
    {
      specifier: "@stepupgaming/comfy-workflows/nodes",
      classes: new Set(Object.keys(bundledDefsJson.defs)),
    },
    ...(opts.registries ?? []),
  ];
  const order = topoSort(g);
  const varName = (id: NodeId): string => {
    const type = g.nodes[id]?.type ?? "node";
    return `${sanitizeIdentifier(lowerCamel(type))}_${id.replace(/[^0-9a-zA-Z]/g, "_")}`;
  };

  // Route each node: first registry that knows its class → typed g.add with
  // the registry's EXACT exported identifier; otherwise rawNode. The
  // identifier used in the import and in the g.add expression is the same
  // resolved value — classTypes that sanitize with collisions still emit
  // working imports.
  const importsBySpecifier = new Map<string, Set<string>>();
  /** nodeId → spec identifier for typed nodes. */
  const specIdent = new Map<NodeId, string>();
  const rawNodes = new Set<NodeId>();
  for (const id of order) {
    const node = g.nodes[id];
    if (!node) continue;
    if (node.raw) {
      rawNodes.add(id);
      continue;
    }
    const registry = registries.find((r) => r.classes.has(node.type));
    if (registry === undefined) {
      // Known to defs but no generated spec available: rawNode keeps the
      // emitted file loadable and the graph compilable. Declare outputs from
      // defs so downstream connections stay wired.
      const def = defs?.[node.type];
      if (def) {
        node.outputTypes = def.outputs.map((o) => o.type);
        node.outputNames = def.outputs.map((o) => o.name ?? o.type);
      }
      rawNodes.add(id);
      continue;
    }
    const ident = registry.identifiers?.get(node.type) ?? sanitizeIdentifier(node.type);
    specIdent.set(id, ident);
    const set = importsBySpecifier.get(registry.specifier) ?? new Set<string>();
    set.add(ident);
    importsBySpecifier.set(registry.specifier, set);
  }

  const hasConnections = Object.values(g.nodes).some((n) => Object.keys(n.inputs).length > 0);
  const hasBypassMaps = Object.values(g.nodes).some(
    (n) => n.bypassMap !== undefined && Object.keys(n.bypassMap).length > 0,
  );
  const lines: string[] = [];
  lines.push(
    "// Generated by `cwf import` — edit freely; this file is now the authoring source.",
  );
  lines.push("// The companion .ir.json preserves the original workflow's raw metadata.");
  lines.push("");
  lines.push('import { workflow } from "@stepupgaming/comfy-workflows";');
  if (hasConnections) lines.push('import { unsafeRef } from "@stepupgaming/comfy-workflows";');
  for (const [specifier, idents] of [...importsBySpecifier.entries()].sort(([a], [b]) =>
    a < b ? -1 : 1,
  )) {
    lines.push(`import { ${[...idents].sort().join(", ")} } from ${JSON.stringify(specifier)};`);
  }
  lines.push('import type { Graph } from "@stepupgaming/comfy-workflows";');
  lines.push("");
  lines.push(`export function build${opts.moduleName ? pascal(opts.moduleName) : ""}(): Graph {`);
  lines.push(`  const g = workflow(${JSON.stringify(g.name ?? "imported")});`);

  for (const id of order) {
    const node = g.nodes[id];
    if (!node) continue;
    const v = varName(id);
    if (rawNodes.has(id)) {
      // Raw nodes preserve EVERYTHING: params, connections (including list
      // inputs), original id, title, mode, and explicit bypassMap.
      const values = emitParams(node.params, 4);
      const conns = emitInputs(node.inputs, varName, 4);
      const rawProps = [values, conns].filter(Boolean).join("\n    ");
      const outputs = (node.outputTypes ?? []).map((t, i) => {
        const name = node.outputNames?.[i];
        return name !== undefined
          ? `{ name: ${JSON.stringify(name)}, type: ${JSON.stringify(t)} }`
          : `{ type: ${JSON.stringify(t)} }`;
      });
      const optsParts: string[] = [];
      if (outputs.length > 0) optsParts.push(`outputs: [${outputs.join(", ")}]`);
      optsParts.push(`id: ${JSON.stringify(id)}`);
      if (node.mode !== undefined && node.mode !== "active") {
        optsParts.push(`mode: ${JSON.stringify(node.mode)}`);
      }
      if (node.title !== undefined) optsParts.push(`title: ${JSON.stringify(node.title)}`);
      lines.push(
        `  const ${v} = g.rawNode(${JSON.stringify(node.type)}, {${rawProps ? `\n    ${rawProps}\n  ` : ""}}, { ${optsParts.join(", ")} });`,
      );
      if (node.bypassMap !== undefined && Object.keys(node.bypassMap).length > 0) {
        lines.push(`  g.setBypassMap(${JSON.stringify(id)}, ${emitBypassMap(node.bypassMap)});`);
      }
      continue;
    }
    const ident = specIdent.get(id) ?? sanitizeIdentifier(node.type);
    const params = emitParams(node.params, 4);
    const conns = emitInputs(node.inputs, varName, 4);
    const props = [params, conns].filter(Boolean).join("\n    ");
    // The NodeSpec expression is the registry's EXACT exported identifier —
    // the same value used in the import statement above.
    lines.push(
      `  const ${v} = g.add(${ident}, {${props ? `\n    ${props}\n  ` : ""}}, { id: ${JSON.stringify(id)} });`,
    );
    if (node.mode === "bypassed" || node.mode === "muted") {
      lines.push(`  g.setMode(${JSON.stringify(id)}, ${JSON.stringify(node.mode)});`);
    }
    if (node.title !== undefined) {
      lines.push(`  g.setTitle(${JSON.stringify(id)}, ${JSON.stringify(node.title)});`);
    }
    if (node.bypassMap !== undefined && Object.keys(node.bypassMap).length > 0) {
      lines.push(`  g.setBypassMap(${JSON.stringify(id)}, ${emitBypassMap(node.bypassMap)});`);
    }
  }

  for (const o of g.outputs) {
    const v = varName(o.node);
    lines.push(
      `  g.output(${v}.out(${o.out})${o.name !== undefined ? `, { name: ${JSON.stringify(o.name)} }` : ""});`,
    );
  }

  lines.push("  return g.toGraph();");
  lines.push("}");
  lines.push("");
  lines.push("export default build" + (opts.moduleName ? pascal(opts.moduleName) : "") + ";");
  return lines.join("\n");
}

/** `{ 0: "model", 1: "clip" }` — keys quoted (JSON keys are always strings). */
function emitBypassMap(map: Record<number, string>): string {
  const entries = Object.keys(map)
    .sort((a, b) => Number(a) - Number(b))
    .map((k) => `${JSON.stringify(k)}: ${JSON.stringify(map[Number(k)])}`);
  return `{ ${entries.join(", ")} }`;
}

function slotExpr(ref: SlotRef, varName: (id: NodeId) => string): string {
  // Uniform untyped connection form: correct for typed and raw sources alike
  // (NodeOutput<never> assigns to any input). Agents can rewire with named
  // typed handles when editing the emitted file by hand.
  return `unsafeRef(${varName(ref.node)}.id, ${ref.out})`;
}

function emitValue(value: ParamValue, indent: number): string {
  if (typeof value === "bigint") return `${value.toString()}n`;
  if (isParamRef(value)) return `g.param(${JSON.stringify(value.$param)}, { type: "string" })`;
  if (value instanceof AssetRef) {
    return `new AssetRef(${JSON.stringify(value.path)}${value.kind !== "image" ? `, ${JSON.stringify(value.kind)}` : ""})`;
  }
  if (Array.isArray(value)) {
    return `[${value.map((v) => emitValue(v, indent + 2)).join(", ")}]`;
  }
  return JSON.stringify(value) ?? "null";
}

function emitParams(params: Record<string, ParamValue>, indent: number): string {
  const parts: string[] = [];
  for (const [name, value] of Object.entries(params)) {
    parts.push(`${JSON.stringify(name)}: ${emitValue(value, indent)},`);
  }
  return parts.join(`\n${" ".repeat(indent)}`);
}

function emitInputs(
  inputs: Record<string, SlotRef | SlotRef[]>,
  varName: (id: NodeId) => string,
  indent: number,
): string {
  const parts: string[] = [];
  for (const [name, ref] of Object.entries(inputs)) {
    if (Array.isArray(ref)) {
      parts.push(`${JSON.stringify(name)}: [${ref.map((r) => slotExpr(r, varName)).join(", ")}],`);
    } else {
      parts.push(`${JSON.stringify(name)}: ${slotExpr(ref, varName)},`);
    }
  }
  return parts.length ? parts.join(`\n${" ".repeat(indent)}`) : "";
}

function pascal(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]+(.)?/g, (_, c: string | undefined) =>
    c ? c.toUpperCase() : "",
  );
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

/** "CLIPTextEncode" → "clipTextEncode" (leading acronym decapitalized as a unit). */
function lowerCamel(s: string): string {
  let i = 0;
  while (i < s.length && /[A-Z]/.test(s[i]) && i + 1 < s.length && /[A-Z]/.test(s[i + 1])) i++;
  if (i === 0) return s.charAt(0).toLowerCase() + s.slice(1);
  return s.slice(0, i).toLowerCase() + s.slice(i);
}
