import { topoSort, type Graph, type NodeId, type ParamValue, type SlotRef } from "../ir/index.js";
import { AssetRef, isParamRef } from "../ir/types.js";
import { sanitizeIdentifier } from "../builder/builder.js";
import type { NodeDefs } from "../defs/index.js";
import bundledDefsJson from "../nodes/gen/defs.json" with { type: "json" };

/**
 * Emit a readable TypeScript workflow file from Graph IR.
 *
 * `comfy import x.json --ts workflows/foo/workflow.ts` turns an imported
 * workflow into authored source: the TS file becomes the canonical authoring
 * representation, the IR file remains the semantic record (including any
 * preserved `source.raw` metadata that has no TS representation).
 *
 * Connections to typed nodes use named handles (`.MODEL`) when defs resolve
 * the output name; everything else falls back to `unsafeRef(...)` — correct,
 * untyped by necessity, and assignable to any input.
 */
export interface EmitterRegistry {
  /** Module specifier to import these specs from (e.g. "./comfy-nodes/registry.js"). */
  specifier: string;
  /** Node classes this registry provides typed specs for. */
  classes: ReadonlySet<string>;
  /** Identifier the registry exports for each class (defaults to classType). */
  identifiers?: ReadonlyMap<string, string>;
}

export function emitTs(
  g: Graph,
  opts: {
    defs?: NodeDefs;
    moduleName?: string;
    /**
     * Typed-spec registries to import from, in priority order. Nodes whose
     * class appears in none of them (and not in the default
     * "comfy-sdk/nodes" registry) are emitted as rawNode() — the emitted file
     * always loads. `comfy import --registry <codegenDir>` wires generated
     * custom-node specs in here automatically.
     */
    registries?: EmitterRegistry[];
  } = {},
): string {
  const defs = opts.defs;
  const registries: EmitterRegistry[] = [
    // Default: the SDK's built-in registry.
    { specifier: "comfy-sdk/nodes", classes: new Set(Object.keys(bundledDefsJson.defs)) },
    ...(opts.registries ?? []),
  ];
  const order = topoSort(g);
  const varName = (id: NodeId): string => {
    const type = g.nodes[id]?.type ?? "node";
    return `${sanitizeIdentifier(lowerCamel(type))}_${id.replace(/[^0-9a-zA-Z]/g, "_")}`;
  };

  // Route each typed node to the first registry that knows its class.
  const importsBySpecifier = new Map<string, Set<string>>();
  const rawNodes = new Set<NodeId>();
  for (const id of order) {
    const node = g.nodes[id];
    if (!node) continue;
    if (node.raw) {
      rawNodes.add(id);
      continue;
    }
    const registry = registries.find((r) => r.classes.has(node.type));
    if (registry === undefined) {
      // Known to defs but no generated spec available: rawNode keeps the
      // emitted file loadable and the graph compilable. Declare outputs from
      // defs so downstream connections stay wired.
      const def = defs?.[node.type];
      if (def) {
        node.outputTypes = def.outputs.map((o) => o.type);
        node.outputNames = def.outputs.map((o) => o.name ?? o.type);
      }
      rawNodes.add(id);
      continue;
    }
    const ident = registry.identifiers?.get(node.type) ?? sanitizeIdentifier(node.type);
    const set = importsBySpecifier.get(registry.specifier) ?? new Set<string>();
    set.add(ident);
    importsBySpecifier.set(registry.specifier, set);
  }

  const hasConnections = Object.values(g.nodes).some((n) => Object.keys(n.inputs).length > 0);
  const lines: string[] = [];
  lines.push(
    "// Generated by `comfy import` — edit freely; this file is now the authoring source.",
  );
  lines.push("// The companion .ir.json preserves the original workflow's raw metadata.");
  lines.push("");
  lines.push('import { workflow } from "comfy-sdk";');
  if (hasConnections) lines.push('import { unsafeRef } from "comfy-sdk";');
  for (const [specifier, idents] of [...importsBySpecifier.entries()].sort(([a], [b]) =>
    a < b ? -1 : 1,
  )) {
    lines.push(`import { ${[...idents].sort().join(", ")} } from ${JSON.stringify(specifier)};`);
  }
  lines.push('import type { Graph } from "comfy-sdk";');
  lines.push("");
  lines.push(`export function build${opts.moduleName ? pascal(opts.moduleName) : ""}(): Graph {`);
  lines.push(`  const g = workflow(${JSON.stringify(g.name ?? "imported")});`);

  for (const id of order) {
    const node = g.nodes[id];
    if (!node) continue;
    const v = varName(id);
    if (rawNodes.has(id)) {
      const values = emitParams(node.params, 4);
      const outputs = (node.outputTypes ?? []).map((t, i) => {
        const name = node.outputNames?.[i];
        return name !== undefined
          ? `{ name: ${JSON.stringify(name)}, type: ${JSON.stringify(t)} }`
          : `{ type: ${JSON.stringify(t)} }`;
      });
      lines.push(
        `  const ${v} = g.rawNode(${JSON.stringify(node.type)}, {${values ? `\n${values}\n  ` : ""}}${
          outputs.length ? `, { outputs: [${outputs.join(", ")}] }` : ""
        });`,
      );
      lines.push(`  void ${v};`);
      continue;
    }
    const params = emitParams(node.params, 4);
    const conns = emitInputs(node.inputs, varName, defs, 4);
    const props = [params, conns].filter(Boolean).join("\n    ");
    lines.push(
      `  const ${v} = g.add(${node.type}, {${props ? `\n    ${props}\n  ` : ""}}, { id: ${JSON.stringify(id)} });`,
    );
    if (node.mode === "bypassed" || node.mode === "muted") {
      lines.push(`  g.setMode(${JSON.stringify(id)}, ${JSON.stringify(node.mode)});`);
    }
    if (node.title !== undefined) {
      lines.push(`  g.setTitle(${JSON.stringify(id)}, ${JSON.stringify(node.title)});`);
    }
  }

  for (const o of g.outputs) {
    const v = varName(o.node);
    lines.push(
      `  g.output(${v}.out(${o.out})${o.name !== undefined ? `, { name: ${JSON.stringify(o.name)} }` : ""});`,
    );
  }

  lines.push("  return g.toGraph();");
  lines.push("}");
  lines.push("");
  lines.push("export default build" + (opts.moduleName ? pascal(opts.moduleName) : "") + ";");
  return lines.join("\n");
}

function slotExpr(ref: SlotRef, varName: (id: NodeId) => string): string {
  // Uniform untyped connection form: correct for typed and raw sources alike
  // (NodeOutput<never> assigns to any input). Agents can rewire with named
  // typed handles when editing the emitted file by hand.
  return `unsafeRef(${varName(ref.node)}.id, ${ref.out})`;
}

function emitValue(value: ParamValue, indent: number): string {
  if (typeof value === "bigint") return `${value.toString()}n`;
  if (isParamRef(value)) return `g.param(${JSON.stringify(value.$param)}, { type: "string" })`;
  if (value instanceof AssetRef) {
    return `new AssetRef(${JSON.stringify(value.path)}${value.kind !== "image" ? `, ${JSON.stringify(value.kind)}` : ""})`;
  }
  if (Array.isArray(value)) {
    return `[${value.map((v) => emitValue(v, indent + 2)).join(", ")}]`;
  }
  return JSON.stringify(value) ?? "null";
}

function emitParams(params: Record<string, ParamValue>, indent: number): string {
  const parts: string[] = [];
  for (const [name, value] of Object.entries(params)) {
    parts.push(`${JSON.stringify(name)}: ${emitValue(value, indent)},`);
  }
  return parts.join(`\n${" ".repeat(indent)}`);
}

function emitInputs(
  inputs: Record<string, SlotRef | SlotRef[]>,
  varName: (id: NodeId) => string,
  defs: NodeDefs | undefined,
  indent: number,
): string {
  void defs;
  const parts: string[] = [];
  for (const [name, ref] of Object.entries(inputs)) {
    if (Array.isArray(ref)) {
      parts.push(`${JSON.stringify(name)}: [${ref.map((r) => slotExpr(r, varName)).join(", ")}],`);
    } else {
      parts.push(`${JSON.stringify(name)}: ${slotExpr(ref, varName)},`);
    }
  }
  return parts.length ? parts.join(`\n${" ".repeat(indent)}`) : "";
}

function pascal(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]+(.)?/g, (_, c: string | undefined) =>
    c ? c.toUpperCase() : "",
  );
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

/** "CLIPTextEncode" → "clipTextEncode" (leading acronym decapitalized as a unit). */
function lowerCamel(s: string): string {
  let i = 0;
  while (i < s.length && /[A-Z]/.test(s[i]) && i + 1 < s.length && /[A-Z]/.test(s[i + 1])) i++;
  if (i === 0) return s.charAt(0).toLowerCase() + s.slice(1);
  return s.slice(0, i).toLowerCase() + s.slice(i);
}
