import type { NodeDef, NodeDefs, DefInput } from "../defs/index.js";
import { serializeComfyJson } from "../json.js";

/**
 * Codegen: NodeDefs → typed wrapper source files.
 *
 * Generated wrappers are `defineNode(...)` spec objects built with the
 * conn/int/float/str/bool/combo helpers — their literal-preserving signatures
 * give each spec exact connection types and required/optional params. Output
 * is deterministic (sorted, stable formatting) so regeneration diffs cleanly.
 *
 * Combos are emitted as widened `string[]` by default (portable across
 * servers — model-file lists differ per machine); `exactCombos` emits literal
 * tuples instead, typing combos as unions (compile fails on other servers'
 * options — regenerate against your instance).
 */

export interface CodegenOptions {
  defs: NodeDefs;
  /** Environment fingerprint stamped into generated headers. */
  objectInfoHash?: string;
  exactCombos?: boolean;
  /**
   * Module specifier generated files import the spec helpers from.
   *
   * Module contract: the codegen output is a DIRECTORY containing
   * `<category>.ts`, `registry.ts`, `defs.json`, `catalog.json`, `NODES.md`;
   * runtime imports resolve through this specifier.
   *
   * - Default `"../../builder/types.js"`: the SDK's own committed
   *   `src/nodes/gen` (fixed in-repo location).
   * - `"comfy-sdk"`: downstream projects generating into arbitrary
   *   directories — helpers resolve via the published package. The CLI
   *   codegen command uses this by default.
   */
  importsFrom?: string;
}

export interface CodegenFile {
  path: string;
  content: string;
}

export interface CodegenResult {
  files: CodegenFile[];
  /** classType → exported identifier (for registries). */
  identifiers: Record<string, string>;
}

export function generateNodeModules(opts: CodegenOptions): CodegenResult {
  const { defs, exactCombos = false } = opts;
  const importsFrom = opts.importsFrom ?? "../../builder/types.js";
  const stamp = [
    "// GENERATED by comfy-sdk codegen — do not edit.",
    opts.objectInfoHash !== undefined ? `// objectInfoHash: ${opts.objectInfoHash}` : undefined,
    `// generatedAt: ${new Date().toISOString()}`,
    "// Regenerate with: comfy codegen",
  ]
    .filter((l) => l !== undefined)
    .join("\n");

  // Group by top-level category.
  const byCategory = new Map<string, NodeDef[]>();
  for (const classType of Object.keys(defs).sort()) {
    const def = defs[classType];
    const category = (def.category || "other").split("/")[0];
    const list = byCategory.get(category) ?? [];
    list.push(def);
    byCategory.set(category, list);
  }

  const identifiers: Record<string, string> = {};
  const usedIdentifiers = new Set<string>([
    // names the generated files must not shadow
    "defineNode",
    "conn",
    "combo",
    "int",
    "float",
    "str",
    "bool",
  ]);
  const files: CodegenFile[] = [];
  const categoryFiles: Array<{ category: string; file: string }> = [];

  for (const category of [...byCategory.keys()].sort()) {
    const defsInCategory = byCategory.get(category) as NodeDef[];
    const slug = slugify(category);
    const file = `${slug}.ts`;
    categoryFiles.push({ category, file });
    const lines: string[] = [
      stamp,
      "",
      `import { bool, combo, conn, defineNode, float, int, str } from ${JSON.stringify(importsFrom)};`,
      "",
    ];

    for (const def of defsInCategory) {
      const ident = uniqueIdentifier(sanitizeIdentifier(def.classType), usedIdentifiers);
      identifiers[def.classType] = ident;
      lines.push(emitSpec(def, ident, exactCombos));
    }
    files.push({ path: file, content: lines.join("\n") + "\n" });
  }

  // Registry.
  const registryLines: string[] = [
    stamp,
    "",
    `import type { NodeSpec } from ${JSON.stringify(importsFrom)};`,
    ...categoryFiles.map(
      (c) => `import * as ${slugify(c.category)} from "./${slugify(c.category)}.js";`,
    ),
    "",
    "/** classType → spec. Covers every node class present in the source defs snapshot. */",
    "export const specs: Record<string, NodeSpec> = {",
    ...Object.keys(identifiers)
      .sort()
      .map((classType) => {
        const def = defs[classType];
        const cat = (def.category || "other").split("/")[0];
        return `  ${JSON.stringify(classType)}: ${slugify(cat)}.${identifiers[classType]},`;
      }),
    "};",
    "",
    // Top-level named re-exports: `import { KSampler } from "comfy-sdk/nodes"`.
    ...Object.keys(identifiers)
      .sort()
      .map((classType) => {
        const def = defs[classType];
        const cat = (def.category || "other").split("/")[0];
        return `export { ${identifiers[classType]} } from "./${slugify(cat)}.js";`;
      }),
    "",
    ...categoryFiles.map((c) => `export { ${slugify(c.category)} };`),
    "",
  ];
  files.push({ path: "registry.ts", content: registryLines.join("\n") });

  // Normalized defs snapshot (machine-readable, consumed by validate/import tools).
  files.push({
    path: "defs.json",
    content:
      serializeComfyJson(
        { format: "comfy-node-defs", version: 1, objectInfoHash: opts.objectInfoHash, defs },
        2,
      ) + "\n",
  });

  // Exact classType -> exported-identifier map. Consumers of a generated
  // directory (e.g. `comfy import --registry`) MUST use this map for emitted
  // imports: sanitized identifiers can collide and get suffixes, so re-deriving
  // names would produce imports that do not exist in the registry.
  files.push({
    path: "identifiers.json",
    content:
      serializeComfyJson(
        {
          format: "comfy-node-identifiers",
          version: 1,
          objectInfoHash: opts.objectInfoHash,
          identifiers,
        },
        2,
      ) + "\n",
  });

  // Catalog (grep-able node discovery) + NODES.md.
  const catalog = buildCatalog(defs);
  files.push({ path: "catalog.json", content: serializeComfyJson(catalog, 2) + "\n" });
  files.push({ path: "NODES.md", content: buildNodesMarkdown(defs, stamp) });

  return { files, identifiers };
}

function emitSpec(def: NodeDef, ident: string, exactCombos: boolean): string {
  const lines: string[] = [];
  if (def.description) {
    lines.push(`/** ${def.description.replace(/\*\//g, "*\\/")} */`);
  }
  const flags = [
    def.outputNode ? "  outputNode: true," : undefined,
    def.deprecated ? "  deprecated: true," : undefined,
    def.experimental ? "  experimental: true," : undefined,
    def.category ? `  category: ${JSON.stringify(def.category)},` : undefined,
  ].filter((l) => l !== undefined);

  lines.push(`export const ${ident} = defineNode(${JSON.stringify(def.classType)}, {`);
  lines.push(...flags);
  lines.push("  inputs: {");
  for (const input of def.inputs) {
    lines.push(`    ${JSON.stringify(input.name)}: ${emitInput(input, exactCombos)},`);
  }
  lines.push("  },");
  // Always emit a name (fallback: the type) so handles get `.LATENT`-style
  // sugar. Names are metadata; identity remains the output index.
  const outputs = def.outputs.map((o) => {
    const name = o.name ?? o.type;
    return `{ name: ${JSON.stringify(name)}, type: ${JSON.stringify(o.type)} }`;
  });
  lines.push(`  outputs: [${outputs.join(", ")}] as const,`);
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

function emitInput(input: DefInput, exactCombos: boolean): string {
  const common: string[] = [];
  if (!input.required) common.push("required: false");
  if (input.tooltip) common.push(`tooltip: ${JSON.stringify(input.tooltip)}`);

  switch (input.kind) {
    case "connection": {
      const args = [JSON.stringify(input.type)];
      if (common.length > 0 || input.forceInput) {
        if (input.forceInput) common.unshift("forceInput: true");
        args.push(`{ ${common.join(", ")} }`);
      }
      return `conn(${args.join(", ")})`;
    }
    case "combo": {
      const options = input.options ?? [];
      const list = exactCombos
        ? `[${options.map((o) => JSON.stringify(o)).join(", ")}] as const`
        : `[${options.map((o) => JSON.stringify(o)).join(", ")}]`;
      const args = [list];
      const comboOpts: string[] = [...common];
      if (input.default !== undefined) comboOpts.push(`default: ${JSON.stringify(input.default)}`);
      if (comboOpts.length > 0) args.push(`{ ${comboOpts.join(", ")} }`);
      return `combo(${args.join(", ")})`;
    }
    case "int": {
      const o: string[] = [...common];
      if (input.default !== undefined) o.push(`default: ${input.default}`);
      if (input.min !== undefined) o.push(`min: ${input.min}`);
      if (input.max !== undefined) o.push(`max: ${input.max}`);
      if (input.step !== undefined) o.push(`step: ${input.step}`);
      if (input.controlAfterGenerate) o.push("controlAfterGenerate: true");
      if (input.forceInput) o.push("forceInput: true");
      return `int({ ${o.join(", ")} })`;
    }
    case "float": {
      const o: string[] = [...common];
      if (input.default !== undefined) o.push(`default: ${input.default}`);
      if (input.min !== undefined) o.push(`min: ${input.min}`);
      if (input.max !== undefined) o.push(`max: ${input.max}`);
      if (input.step !== undefined) o.push(`step: ${input.step}`);
      if (input.round !== undefined) o.push(`round: ${input.round}`);
      if (input.forceInput) o.push("forceInput: true");
      return `float({ ${o.join(", ")} })`;
    }
    case "string": {
      const o: string[] = [...common];
      if (input.default !== undefined) o.push(`default: ${JSON.stringify(input.default)}`);
      if (input.multiline) o.push("multiline: true");
      if (input.dynamicPrompts) o.push("dynamicPrompts: true");
      if (input.placeholder) o.push(`placeholder: ${JSON.stringify(input.placeholder)}`);
      if (input.forceInput) o.push("forceInput: true");
      return `str({ ${o.join(", ")} })`;
    }
    case "boolean": {
      const o: string[] = [...common];
      if (input.default !== undefined) o.push(`default: ${String(input.default)}`);
      if (input.forceInput) o.push("forceInput: true");
      return `bool({ ${o.join(", ")} })`;
    }
  }
}

export interface CatalogEntry {
  classType: string;
  displayName: string;
  category: string;
  inputs: Array<{ name: string; kind: string; type?: string }>;
  outputs: Array<{ name?: string; type: string }>;
  outputNode: boolean;
  deprecated?: boolean;
  experimental?: boolean;
}

export function buildCatalog(defs: NodeDefs): { objectInfoHash?: string; nodes: CatalogEntry[] } {
  return {
    nodes: Object.keys(defs)
      .sort()
      .map((classType) => {
        const def = defs[classType];
        return {
          classType,
          displayName: def.displayName,
          category: def.category,
          inputs: def.inputs.map((i) => ({
            name: i.name,
            kind: i.kind,
            ...(i.kind === "connection" ? { type: i.type } : {}),
          })),
          outputs: def.outputs.map((o) => ({
            type: o.type,
            ...(o.name !== undefined ? { name: o.name } : {}),
          })),
          outputNode: def.outputNode,
          ...(def.deprecated ? { deprecated: true } : {}),
          ...(def.experimental ? { experimental: true } : {}),
        };
      }),
  };
}

function buildNodesMarkdown(defs: NodeDefs, stamp: string): string {
  const lines: string[] = [
    "<!-- " + stamp.replace(/\n /g, " ") + " -->",
    "",
    "# Comfy node catalog",
    "",
  ];
  const byCategory = new Map<string, NodeDef[]>();
  for (const classType of Object.keys(defs).sort()) {
    const def = defs[classType];
    const cat = def.category || "other";
    const list = byCategory.get(cat) ?? [];
    list.push(def);
    byCategory.set(cat, list);
  }
  for (const cat of [...byCategory.keys()].sort()) {
    lines.push(`## ${cat}`, "");
    for (const def of byCategory.get(cat) as NodeDef[]) {
      const inputs = def.inputs
        .map((i) =>
          i.kind === "connection"
            ? `${i.name}:${i.type}`
            : `${i.name}:${i.kind}${i.required ? "" : " (opt)"}`,
        )
        .join(", ");
      const outputs = def.outputs.map((o) => o.type).join(", ") || "—";
      const flags = def.deprecated ? " (deprecated)" : def.experimental ? " (experimental)" : "";
      lines.push(`- **${def.classType}**${flags} — in: ${inputs || "—"} · out: ${outputs}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function slugify(name: string): string {
  return (
    name
      .replace(/[^A-Za-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .replace(/^(\d)/, "_$1") || "other"
  );
}

function sanitizeIdentifier(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_$]/g, "_");
  if (/^[0-9]/.test(cleaned) || cleaned === "") return `_${cleaned}`;
  return cleaned;
}

function uniqueIdentifier(base: string, used: Set<string>): string {
  if (!used.has(base)) {
    used.add(base);
    return base;
  }
  let i = 2;
  while (used.has(`${base}_${i}`)) i++;
  const candidate = `${base}_${i}`;
  used.add(candidate);
  return candidate;
}
