#!/usr/bin/env node
/**
 * Generate docs reference fragments from source. Run from repo root.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync, readFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "docs", "reference", "_generated");

function extractErrorCodes(src) {
  const block = src.match(/export const ErrorCodes = \{([\s\S]*?)\} as const;/);
  if (!block) throw new Error("Could not find ErrorCodes in src/errors.ts");
  const rows = [];
  const re = /\/\*\* ([^*]+) \*\/\s*\n\s*\w+: "([^"]+)"/g;
  let m;
  while ((m = re.exec(block[1]))) {
    rows.push({ code: m[2], meaning: m[1].trim() });
  }
  if (rows.length === 0) throw new Error("No ErrorCodes extracted");
  return rows;
}

function extractCliHelp(src) {
  const fn = src.match(/function printHelp\(\): void \{[\s\S]*?process\.stdout\.write\(\s*\[([\s\S]*?)\]\.join\("\\n"\)/);
  if (!fn) throw new Error("Could not find printHelp in src/cli/cli.ts");
  const lines = [...fn[1].matchAll(/"([^"]*)"/g)].map((m) => m[1]);
  return lines.join("\n").replace(/\\n/g, "\n");
}

function extractCommands(help) {
  const commands = [];
  for (const line of help.split("\n")) {
    const m = line.trim().match(/^cwf ([a-z][\w-]*)/);
    if (m) commands.push(m[1]);
  }
  return [...new Set(commands)];
}

const errorsSrc = await readFile(join(root, "src", "errors.ts"), "utf8");
const cliSrc = await readFile(join(root, "src", "cli", "cli.ts"), "utf8");
const pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8"));

const codes = extractErrorCodes(errorsSrc);
const help = extractCliHelp(cliSrc);
const commands = extractCommands(help);

await mkdir(outDir, { recursive: true });

const errorMd = [
  "<!-- GENERATED by scripts/docs-gen.mjs — do not edit. -->",
  "",
  "| Code | Meaning |",
  "| ---- | ------- |",
  ...codes.map((r) => `| \`${r.code}\` | ${r.meaning} |`),
  "",
].join("\n");

const cliMd = [
  "<!-- GENERATED by scripts/docs-gen.mjs — do not edit. -->",
  "",
  "```",
  help.trim(),
  "```",
  "",
].join("\n");

const catalog = {
  version: pkg.version,
  generatedAt: new Date().toISOString(),
  errorCodes: codes.map((r) => r.code),
  cliCommands: commands,
};

await writeFile(join(outDir, "error-codes.md"), errorMd);
await writeFile(join(outDir, "cli-help.md"), cliMd);
await writeFile(join(outDir, "catalog.json"), JSON.stringify(catalog, null, 2) + "\n");

const distCatalog = JSON.parse(await readFile(join(root, "distribution", "packages.json"), "utf8"));
let distStatus = { packages: [] };
const statusPath = join(root, "distribution", "status.json");
if (existsSync(statusPath)) {
  distStatus = JSON.parse(readFileSync(statusPath, "utf8"));
}
const statusByName = new Map((distStatus.packages ?? []).map((p) => [p.name, p]));
const indexRows = [];
for (const entry of distCatalog.packages) {
  const pj = JSON.parse(await readFile(join(root, entry.dir, "package.json"), "utf8"));
  const st = statusByName.get(entry.name) ?? {};
  const version = pj.version;
  const tarball = `${entry.name.replace(/^@/, "").replace("/", "-")}-${version}.tgz`;
  const tag = `v${distStatus.version ?? pkg.version}`;
  const releaseUrl = `https://github.com/stepupgaming/comfy-workflows/releases/tag/${tag}`;
  const npmStatus = st.npmMirrorStatus ?? (entry.npmMirrorEligible ? "unknown" : "not-requested");
  indexRows.push({
    name: entry.name,
    version,
    kind: entry.kind,
    family: entry.family,
    description: pj.description ?? entry.description,
    tarball,
    releaseUrl,
    npmStatus,
  });
}
const indexMd = [
  "<!-- GENERATED by scripts/docs-gen.mjs — do not edit. -->",
  "",
  "Canonical host: **GitHub Packages** (authenticated) and **GitHub Release tarballs** (anonymous).",
  "npmjs is a convenience mirror when the name exists there.",
  "",
  "| Package | Version | Family | GitHub Packages | Release tarball | npm mirror |",
  "| ------- | ------- | ------ | --------------- | --------------- | ---------- |",
  ...indexRows.map((r) => {
    const unscoped = r.name.replace(/^@[^/]+\//, "");
    const pkgUrl = `https://github.com/stepupgaming/comfy-workflows/pkgs/npm/${unscoped}`;
    const npmCell =
      r.npmStatus === "mirrored"
        ? `[mirrored](https://www.npmjs.com/package/${r.name})`
        : r.npmStatus;
    return `| \`${r.name}\` | ${r.version} | ${r.family} | [package](${pkgUrl}) | [${r.tarball}](${r.releaseUrl}) | ${npmCell} |`;
  }),
  "",
].join("\n");
await writeFile(join(outDir, "package-index.md"), indexMd);

await import("./agent-docs.mjs");

process.stdout.write(
  `docs-gen: ${codes.length} error codes, ${commands.length} CLI commands, ${indexRows.length} packages, v${pkg.version}\n`,
);
